//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Emlak.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AJANDA
    {
        public long AjandaID { get; set; }
        public long UserID { get; set; }
        public Nullable<System.DateTime> Tarih { get; set; }
        public string Nerede { get; set; }
        public string Kiminle { get; set; }
        public string Konu { get; set; }
        public string Note { get; set; }
    
        public virtual USERS USERS { get; set; }
    }
}
