//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Emlak.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ARSA_TARLA
    {
        public long ID { get; set; }
        public Nullable<System.DateTime> Tarih { get; set; }
        public string ImarDurumu { get; set; }
        public string Belediye { get; set; }
        public Nullable<int> Ada { get; set; }
        public Nullable<int> Parsel { get; set; }
        public Nullable<int> MetreKare { get; set; }
        public Nullable<bool> KatKarsiligiOlabilir { get; set; }
        public Nullable<bool> Takas { get; set; }
        public string TapuDurumu { get; set; }
        public Nullable<bool> IskanDurumu { get; set; }
        public Nullable<bool> KonutImarli { get; set; }
        public Nullable<bool> TicariImarli { get; set; }
        public string Kira_Satilik { get; set; }
        public string picture1 { get; set; }
        public string picture2 { get; set; }
        public string picture3 { get; set; }
        public string picture4 { get; set; }
        public string picture5 { get; set; }
        public string picture6 { get; set; }
        public string picture7 { get; set; }
        public string picture8 { get; set; }
        public string picture9 { get; set; }
        public string picture10 { get; set; }
        public string picture11 { get; set; }
        public string picture12 { get; set; }
        public string picture13 { get; set; }
        public string picture14 { get; set; }
        public string picture15 { get; set; }
        public string picture16 { get; set; }
        public string picture17 { get; set; }
        public string picture18 { get; set; }
        public string picture19 { get; set; }
        public string picture20 { get; set; }
        public string picture21 { get; set; }
        public string picture22 { get; set; }
        public string picture23 { get; set; }
        public string picture24 { get; set; }
        public string picture25 { get; set; }
        public long UserID { get; set; }
    
        public virtual USERS USERS { get; set; }
    }
}
