//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Emlak.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BorcluTakip
    {
        public long BorcluTakipID { get; set; }
        public Nullable<long> MusteriID { get; set; }
        public string MusteriAd { get; set; }
        public string MusteriSoyAd { get; set; }
        public string MusteriCep { get; set; }
        public Nullable<int> OdemeTL { get; set; }
        public Nullable<System.DateTime> OdemeTarihi { get; set; }
        public string Note { get; set; }
    
        public virtual MUSTERI MUSTERI { get; set; }
    }
}
