//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Emlak.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmlakArayanlar
    {
        public long ArayanlarID { get; set; }
        public string ArayanAd { get; set; }
        public string ArayanSoyAd { get; set; }
        public string Cep { get; set; }
        public string IsTel { get; set; }
        public string Kiraci_Alici { get; set; }
        public Nullable<int> EmlakTuru { get; set; }
        public Nullable<int> MetreKare { get; set; }
        public Nullable<int> Fiyat { get; set; }
        public Nullable<int> OdaSayisi { get; set; }
        public Nullable<int> BinaYasi { get; set; }
        public Nullable<int> KacinciKat { get; set; }
        public string Note { get; set; }
        public long UserID { get; set; }
    
        public virtual EMLAKTURU EMLAKTURU1 { get; set; }
        public virtual ODA_SAYISI ODA_SAYISI { get; set; }
        public virtual USERS USERS { get; set; }
    }
}
