//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Emlak.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KontratTakip
    {
        public long KontratTakipID { get; set; }
        public string Ad { get; set; }
        public string SoyAd { get; set; }
        public string TC { get; set; }
        public string Cep { get; set; }
        public Nullable<System.DateTime> OdemeTarihi { get; set; }
        public Nullable<int> KaçAy { get; set; }
        public Nullable<int> Kalan { get; set; }
        public string Note { get; set; }
    }
}
