//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Emlak.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KONUT_ISYERI
    {
        public long ID { get; set; }
        public string MusteriKaynagi { get; set; }
        public string Adi { get; set; }
        public string Soyadi { get; set; }
        public string TC { get; set; }
        public string Iban { get; set; }
        public string CepTelefonu { get; set; }
        public string IsTelefonu { get; set; }
        public Nullable<System.DateTime> Tarih { get; set; }
        public string il { get; set; }
        public string ilce { get; set; }
        public string Mahalle { get; set; }
        public string Cadde { get; set; }
        public string Sokak { get; set; }
        public string AptAdi { get; set; }
        public Nullable<int> AptNo { get; set; }
        public Nullable<int> DaireNo { get; set; }
        public string Kira_Satilik { get; set; }
        public string Isyeri_Konut { get; set; }
        public Nullable<int> MetreKare { get; set; }
        public Nullable<int> BinaYasi { get; set; }
        public Nullable<int> KatSayisi { get; set; }
        public Nullable<int> Kat { get; set; }
        public Nullable<int> OdaSayisi { get; set; }
        public Nullable<int> IsitmaTipi { get; set; }
        public Nullable<int> BanyoSayisi { get; set; }
        public Nullable<int> FiyatNet { get; set; }
        public Nullable<int> FiyatSatis { get; set; }
        public Nullable<bool> EsyaliMi { get; set; }
        public Nullable<int> DepozitTL { get; set; }
        public Nullable<int> EmlakTuru { get; set; }
        public string Note { get; set; }
        public Nullable<bool> DevrenSatilik { get; set; }
        public Nullable<bool> DevrenKiralik { get; set; }
        public string picture1 { get; set; }
        public string picture2 { get; set; }
        public string picture3 { get; set; }
        public string picture4 { get; set; }
        public string picture5 { get; set; }
        public string picture6 { get; set; }
        public string picture7 { get; set; }
        public string picture8 { get; set; }
        public string picture9 { get; set; }
        public string picture10 { get; set; }
        public string picture11 { get; set; }
        public string picture12 { get; set; }
        public string picture13 { get; set; }
        public string picture14 { get; set; }
        public string picture15 { get; set; }
        public string picture16 { get; set; }
        public string picture17 { get; set; }
        public string picture18 { get; set; }
        public string picture19 { get; set; }
        public string picture20 { get; set; }
        public string picture21 { get; set; }
        public string picture22 { get; set; }
        public string picture23 { get; set; }
        public string picture24 { get; set; }
        public string picture25 { get; set; }
        public long UserID { get; set; }
    
        public virtual EMLAKTURU EMLAKTURU1 { get; set; }
        public virtual ISITMA_TIPI ISITMA_TIPI { get; set; }
        public virtual ODA_SAYISI ODA_SAYISI { get; set; }
        public virtual USERS USERS { get; set; }
    }
}
