//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Emlak.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MAKBUZ_SOZLESME
    {
        public long MakbuzSozlesmeID { get; set; }
        public string KiraciAdi { get; set; }
        public string KiraciSoyAdi { get; set; }
        public string KiraciTCKimlik { get; set; }
        public string Cep { get; set; }
        public Nullable<int> KacAy { get; set; }
        public Nullable<int> AylikOdemeTL { get; set; }
        public Nullable<System.DateTime> OdemeBaslangicTarihi { get; set; }
        public string KiracininAdresi { get; set; }
        public Nullable<int> Ay1 { get; set; }
        public Nullable<int> Ay2 { get; set; }
        public Nullable<int> Ay3 { get; set; }
        public Nullable<int> Ay4 { get; set; }
        public Nullable<int> Ay5 { get; set; }
        public Nullable<int> Ay6 { get; set; }
        public Nullable<int> Ay7 { get; set; }
        public Nullable<int> Ay8 { get; set; }
        public Nullable<int> Ay9 { get; set; }
        public Nullable<int> Ay10 { get; set; }
        public Nullable<int> Ay11 { get; set; }
        public Nullable<int> Ay12 { get; set; }
        public Nullable<bool> KirmiziList { get; set; }
        public Nullable<bool> Borclu { get; set; }
        public Nullable<bool> KiraTakip { get; set; }
        public Nullable<bool> Depozit { get; set; }
        public Nullable<int> DepozitTL { get; set; }
        public string DanismanAd { get; set; }
        public string DanismanSoyAd { get; set; }
        public string KirayaVerenAdi { get; set; }
        public string KirayaVerenSoyAdi { get; set; }
        public string KirayaVerenTC { get; set; }
        public string KirayaVerenIBAN { get; set; }
        public string KirayaVerenCep { get; set; }
        public string IL { get; set; }
        public string ILCE { get; set; }
        public string Mahalle { get; set; }
        public string Cadde { get; set; }
        public string Sokak { get; set; }
        public string SiteAdi { get; set; }
        public string BlokAdi { get; set; }
        public string AptAdi { get; set; }
        public Nullable<int> AptNo { get; set; }
        public Nullable<int> Kat { get; set; }
        public Nullable<int> DaireNo { get; set; }
        public string EmlakTuru { get; set; }
        public string KirayaVerenAdres { get; set; }
        public string Note { get; set; }
        public Nullable<long> userID { get; set; }
        public Nullable<long> KonutID { get; set; }
        public Nullable<long> ArsaTarlaID { get; set; }
        public Nullable<long> BinaID { get; set; }
    
        public virtual ARSA_TARLA ARSA_TARLA { get; set; }
        public virtual BINA BINA { get; set; }
        public virtual KONUT_ISYERI KONUT_ISYERI { get; set; }
        public virtual USERS USERS { get; set; }
    }
}
