//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Emlak.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MESAJ
    {
        public long MesajID { get; set; }
        public Nullable<long> Kimden { get; set; }
        public Nullable<long> Kime { get; set; }
        public string isim { get; set; }
        public string soyisim { get; set; }
        public string Mesaj1 { get; set; }
    
        public virtual USERS USERS { get; set; }
        public virtual USERS USERS1 { get; set; }
    }
}
