//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Emlak.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MUSTERI
    {
        public long MusteriID { get; set; }
        public string MusteriAd { get; set; }
        public string MusteriSoyAd { get; set; }
        public string MusteriTC { get; set; }
        public string MusteriCep { get; set; }
        public string MusteriIsTelefonu { get; set; }
        public string Adres { get; set; }
        public Nullable<int> MusteriTipi { get; set; }
        public long UserID { get; set; }
        public string Note { get; set; }
    
        public virtual MUSTERI_TIPI MUSTERI_TIPI { get; set; }
        public virtual USERS USERS { get; set; }
    }
}
